made progress towards converting project from JS to TS, still needs work
MustafaAliDS/SpotifyAPI-Project pull request #3
Opened 2022-06-30 01:59 UTC by MustafaAliDS

-  Works up to first get request and gets the callback link along with the stringqueried parameters 

- Biggest issues are encoding the combined IDs and using them in the header for authOptions on line 35. I had to change it from Buffer.from()
because TypeScript does not like that it's depricated. New method is causing issues. 
minor issue related to this: combinedIDs is not read according to TypeScript, but it's being used in the encode function on line 32. 

- Another issue that I am not sure messed things up is the code property in the form object nested in authOptions. 
It's undefined before it's  received from req.body.code, so I added a question mark req.body?.code
Not sure if that messed things up. I did this because TypeScript freaks out if I put that the type is either string or null

2022-06-30 02:46 UTC, MustafaAliDS commented
https://prod.liveshare.vsengsaas.visualstudio.com/join?9BCC2770C77E3C48AB1B33B154DBC066FAEF

2022-07-01 00:50 UTC, MichaelAlexanderBanuelos reviewed
this is a great start. i can approve after the comments have been resolved

2022-07-01 00:50 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +const APP: Application = express();
```suggestion
const server: Application = express();
```

`nit`: we should only the all caps pattern when dealing with strings that never change

2022-07-01 00:50 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +const CLIENT_SECERET = process.env["CLIENT_SECERET"];
❤️

2022-07-01 00:50 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +  console.log(CLIENT_SECERET);
we should be able to remove these and in general shouldn't have `console.log`s on `main` unless truly needed

2022-07-01 00:50 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +      let expires_in: string = body.expires_in;
```suggestion
      let access_token = body.access_token;
      let token_type = body.token_type;
      let scope = body.scope;
      let expires_in = body.expires_in;
```

`nit`: the typescript compiler should be able to infer the type at this point

2022-07-01 00:51 UTC, MichaelAlexanderBanuelos commented
another thing we can do that will be needed as we expand this server, is creating a routes file / controller that handles different paths

2022-07-01 01:07 UTC, MustafaAliDS commented on src/server.ts
> +      let expires_in: string = body.expires_in;
Removing them and hovering over the variables shows "let variablesName: any". Is that fine? 

![infer](https://user-images.githubusercontent.com/78193284/176802801-f23a373b-8981-4292-9adc-2fe53466d2cc.PNG)

2022-07-01 01:21 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +  console.log(CLIENT_SECERET);
can you try using `_` instead of `req` and see if it still complains about it not being used?

2022-07-01 01:22 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +      let expires_in: string = body.expires_in;
_interesting_. lets leave it for now

2022-07-01 01:52 UTC, MichaelAlexanderBanuelos approved these changes
LGTM

2022-07-04 01:37 UTC, MichaelAlexanderBanuelos approved these changes
LGTM

2022-07-04 01:45 UTC, MichaelAlexanderBanuelos requested changes

2022-07-04 01:45 UTC, MichaelAlexanderBanuelos commented on src/server.ts
> +interface body {
typically we define types and interfaces in [PascalCase](https://stackoverflow.com/a/29603511)

2022-07-04 01:48 UTC, MichaelAlexanderBanuelos approved these changes

2022-07-04 01:50 UTC, merged